spring:
    profiles:
        active:
            - dev
            
---
spring:
    profiles:
        application:
            name: microservicecloud-config-yuhe-dev
            
---
spring:
    profiles:
        application:
            name: microservicecloud-config-yuhe-test